### ISSUE TITLE
Refresh Rate & Wind Speed Unit

### ISSUE THREAD

**Issue by lanky8804** [siku2/hass-weatherlink#1]
Just found this, installed and loving it.

Couple of questions really, what's the refresh rate? Also anyway to get wind speed in kts?

Thanks for all the hard work :)

**Comment by siku2** [comment]
Oh, hello. I wrote this mostly for myself so I didn't expect anyone else to be using it.
The refresh rate is currently hard-coded to 30 seconds here:
https://github.com/siku2/hass-weatherlink/blob/44aaad759b3d4ecb98ec2804e3c852db19f3479e/custom_components/weatherlink/__init__.py#L44-L53

As for converting the wind speed to knots, that's something that could be added fairly easily.
It would have to be an option, of course.

**Comment by lanky8804** [comment]
Excellent thank you. I see you are looking at unit covertions also. Wind going to N, E, S, W etc maybe?

I tried implementing this in HA but my coding knowledge is limtited and was based on what other were talking about.

`    vantage_wind_dir_last_NESW:
      friendly_name: 'Vantage Wind Direction NESW'
        value_template: >
          {% set direction = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW','N'] %}
          {% set degree = states('sensor.vantage_wind_dir_last')|float %}
          {{ direction[((degree+11.25)/22.5)|int] }}`

**Comment by NRutt2005** [comment]
@siku2, This is a great custom integration for Home Assistant! Thank you for sharing! I would agree with @lanky8804, if you are willing to update this custom integration to show in different units of measurements and also the wind direction showing N, NNE, NE, ENE, E, ESE, SE, SSE, S, SSW, SW, WSW ,W, WNW, NW, NNW, N instead of the degrees, that would be amazing. On the different units of measurements, I would love to see inches for rainfall and MPH for wind speed and be able to see inches of mercury (Hg) for us weird Americans that use the imperial system. I wish I knew coding so I could help contribute to your integration but thank you again for sharing!
