### ISSUE TITLE
Listen to real time broadcasts

### ISSUE THREAD

**Issue by siku2** [siku2/hass-weatherlink#8]
Reference: <https://weatherlink.github.io/weatherlink-live-local-api#real-time-data-broadcast-through-udp>

**Comment by cambmint** [comment]
Trying this now, I'm seeing Rain Today updating every few seconds - what looks like the correct value flickers up very briefly, but the 'held' value is being displayed as '0 mm' (it should be reading '8.8 mm'). Rain Rate is also flickering with updates but otherwise '0 mm/h'. All other entries - Wind/Max/Direction, Temperature, Solar, UV etc - have stopped updating altogether. The Update Interval is currently set to 30s, and I've restarted the server between tests.

**Comment by siku2** [comment]
> All other entries - Wind/Max/Direction, Temperature, Solar, UV etc - have stopped updating altogether.

That's a known issue and will be fixed in 5.0.1. Regarding the other issues, you should really create a new issue instead of commenting on a closed one.
